### PR TITLE
calculator

### PR DESCRIPTION
**Pull request by wiredlime**

### CODE REVIEW

**Comment by chug2k** [comment]
This is overall good "porting" (e.g. translating) work, and I realize you didn't create this @wiredlime , but I have some suggestions 😇 for how it could be improved. I think we can work on making this exercise an "ideal" example that other people can follow in the future. This will be the CHOSEN ONE.

## Some principles
1.  Design the smallest possible complete loops, and build incrementally. 
2. Offer solutions for the smallest loops, but leave small tasks to the reader. 
3. Anticipate common problems and pitfalls. 

## Overall Problems with this assignment
This seems like someone advanced simply took a calculator app and just built it, and documented building it. Anyone can do that. But an educator should think of the main concepts involved and try to demonstrate the minimum of each one, and let learners build upon them. 

In other words, one potential way to build it is like this - it's a bit extreme but I really want to emphasize the rant I just gave.

### Suggested New Flow

1. Build an app with two textboxes and a `=` button. When you click the button, the app outputs the sum of the two numbers that are typed in. Note that this also covers your `parseInt` situation. (Only support integers for now; keep it as simple as possible.)
2. Now add in a radio button, that is labeled "operator". They can select either `+` or `-`. Implement this. 
3. Now ask the learner to add in `*` and `/`. This should be easy for them, but if they don't understand the previous steps, they will die here. 💀 
4. Now switch from a radio button, to just buttons, where the last one you click is recorded. 
5. Now create the number pad for the first operand. Only support one digit numbers. 
6. Normally, I think having a second number pad would be my instinct, but I think that'll make things more confusing here. So now it becomes the exercise of the `num1` and `num2` thing - you need to figure out which one you need to set. 
7. Now we have a fully functioning calculator! Wait, no we don't. Now we need to implement multiple digit numbers. 
8. Now we have a fully functioning calculator! Wait, no we don't. Now we need to implement decimal points. 
9. Now we have a fully functioning calculator! Wait, no we don't. Now we need to implement chaining. 

### Benefits of this flow

Breaking this up into smaller pieces makes it easier to learn, because you see the results of what you're typing right away. The shorter the distance between coding and result, the easier it is to learn from your mistakes. 

This also gives the benefit of the learner feeling accomplishment sooner, which is generally motivating. Games where you're constantly winning make you want to keep playing. Even while writing these instructions, I started to feel some real momentum while I was typing. 

The breakpoint on Step 3 means that if you understand nothing, you won't get to the end. You'll be dead on adding multiply/divide, which should be trivial if you know what's going on. This is overall a good thing, because if you don't understand the basics, time spent on more advanced things is generally wasted (and demotivating). 

Last but not least, it makes it easier to understand the goal at each step, which makes it easier to ask questions. Now a learner question is hopefully more like "How do I implement * and /" instead of "this code on line 34 doesn't work".

**Comment by chug2k** [comment]
@wiredlime do you think you could try reorganizing this assignment? I'm not entirely unhappy to do it myself because it would be fun to learn content 2.0,  but I would probably be much happier if you could do it since that would mean you get where I'm coming from.

**Comment by wiredlime** [comment]
Cool approach! So we want a How-to instead of a Solution.
This’s really interesting ~~might as well be difficult~~ and I don’t think there are so many people doing this kind of content out there, heumm. 
If so please ref me a few of them since the artist needs inspos. 

I’ll start with your Suggested New Flow while consulting anh Tuan and anh Minh along the way. 

Thanks.

**Comment by lukehoang1905** [comment]
@chug2k I will assist @wiredlime to re organize this

**Pull request merged**
